/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthVideoImport } from './routes/_auth/video'
import { Route as AuthTelevisionImport } from './routes/_auth/television'
import { Route as AuthProfileImport } from './routes/_auth/profile'
import { Route as AuthMovieImport } from './routes/_auth/$movie'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthVideoRoute = AuthVideoImport.update({
  path: '/video',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTelevisionRoute = AuthTelevisionImport.update({
  path: '/television',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMovieRoute = AuthMovieImport.update({
  path: '/$movie',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/$movie': {
      preLoaderRoute: typeof AuthMovieImport
      parentRoute: typeof AuthImport
    }
    '/_auth/profile': {
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthImport
    }
    '/_auth/television': {
      preLoaderRoute: typeof AuthTelevisionImport
      parentRoute: typeof AuthImport
    }
    '/_auth/video': {
      preLoaderRoute: typeof AuthVideoImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthMovieRoute,
    AuthProfileRoute,
    AuthTelevisionRoute,
    AuthVideoRoute,
    AuthIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
